version: '3.8'
services:
  db-crawler:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=your-openai-key-here
    volumes:
      - .:/app
    restart: unless-stopped
